#! /bin/sh

# Defaults
csrinit="y"
btdev="/dev/bt"
btif="hci0"
btmulaw="0"

mkdir -p /etc/bluetooth/

# Setup variables to be inherited by called shell scripts
    for i in /proc/barcelona/*; do
      export hw_${i##*/}="$(cat $i)"
    done

if ! sed "s/@DEVNAME@/${hw_btname}/;s/@DEVCLASS@/${hw_btclass}/" \
	/usr/local/etc/hcid.conf.template > /etc/bluetooth/hcid.conf; then
    die "unable to setup hcid config file"
fi

if test "${csrinit}" = "y"; then
  if test "${hw_btusb}" = "0"; then
    if ! csrinit bcsp ${btdev} ${hw_btspeed} ${hw_btclock}; then
      die "csrinit failed"
    fi
  elif ! csrinit usb ${btdev} ${hw_btspeed} ${hw_btclock}; then
    echo "csrinit usb failed, trying bcsp"
    if ! csrinit bcsp ${btdev} ${hw_btspeed} ${hw_btclock}; then
      die "csrinit bcsp failed too"
    fi
  fi
fi


if test "${hw_btusb}" = "0" && ! hciattach /dev/bt bcsp ${hw_btspeed}; then
  die "hciattach failed"
fi

if ! hciconfig ${btif} up; then
  die "hciconfig failed"
fi
